export const FETCH_NOTES: string = "FETCH_NOTES";
export const FETCH_NOTES_SUCCESS: string = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_ERROR: string = "FETCH_NOTES_ERROR";

const VALID_BLACK_KEYS: string[] = [
    "2",
    "3",
    "5",
    "6",
    "7",
    "s",
    "d",
    "g",
    "h",
    "j",
];

const VALID_WHITE_KEYS: string[] = [
    "q",
    "w",
    "e",
    "r",
    "t",
    "y",
    "u",
    "z",
    "x",
    "c",
    "v",
    "b",
    "n",
    "m",
];

export const VALID_KEYS: string[] = [...VALID_BLACK_KEYS, ...VALID_WHITE_KEYS];

export const NOTES: any[] = [
    {note: "C3", code: "q"},
    {note: "Db3", code: "2"},
    {note: "D3", code: "w"},
    {note: "Eb3", code: "3"},
    {note: "E3", code: "e"},
    {note: "F3", code: "r"},
    {note: "Gb3", code: "5"},
    {note: "G3", code: "t"},
    {note: "Ab3", code: "6"},
    {note: "A3", code: "y"},
    {note: "Bb3", code: "7"},
    {note: "B3", code: "u"},
    {note: "C4", code: "z"},
    {note: "Db4", code: "s"},
    {note: "D4", code: "x"},
    {note: "Eb4", code: "d"},
    {note: "E4", code: "c"},
    {note: "Gb4", code: "g"},
    {note: "F4", code: "v"},
    {note: "G4", code: "b"},
    {note: "Ab4", code: "h"},
    {note: "A4", code: "n"},
    {note: "Bb4", code: "j"},
    {note: "B4", code: "m"},
];

export const KEYS: string[] = [
    "q",
    "2",
    "w",
    "3",
    "e",
    "r",
    "5",
    "t",
    "6",
    "y",
    "7",
    "u",
    "z",
    "s",
    "x",
    "d",
    "c",
    "g",
    "v",
    "b",
    "h",
    "n",
    "j",
    "m",
];

export const NOTE_TO_KEY: {[key: string]: string} = {
    C3: "q",
    Db3: "2",
    D3: "w",
    Eb3: "3",
    E3: "e",
    F3: "r",
    Gb3: "5",
    G3: "t",
    Ab3: "6",
    A3: "y",
    Bb3: "7",
    B3: "u",
    C4: "z",
    Db4: "s",
    D4: "x",
    Eb4: "d",
    E4: "c",
    Gb4: "g",
    F4: "v",
    G4: "b",
    Ab4: "h",
    A4: "n",
    Bb4: "j",
    B4: "m",
};

export const KEY_TO_NOTE: {[key: string]: string} = {
    q: "C3",
    2: "Db3",
    w: "D3",
    3: "Eb3",
    e: "E3",
    r: "F3",
    5: "Gb3",
    t: "G3",
    6: "Ab3",
    y: "A3",
    7: "Bb3",
    u: "B3",
    z: "C4",
    s: "Db4",
    x: "D4",
    d: "Eb4",
    c: "E4",
    g: "Gb4",
    v: "F4",
    b: "G4",
    h: "Ab4",
    n: "A4",
    j: "Bb4",
    m: "B4",
};
